main:
  email: from1@example.com
  password: p4ssw0rd

bil101:
  teacher: Recai Oktaş
  hw_name: deneme
  email: from2@example.com
  end_date: 2011-12-30

bil202:
  teacher: Onur Baran
  hw_name: deneme
  email: from3@example.com
  end_date: 2011-12-29
